---
# The playbook will configure the bare minimum needed for an Ubuntu server.

- hosts: localhost
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install desired packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
            - aptitude
            - iftop
            - tree
            - wget

      - name: Configure Vagrant .ssh directory
        file: path=/home/vagrant/.ssh state=directory owner=vagrant group=vagrant mode=0700

      - name: Get Vagrant's public key
        get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
                 dest=/home/vagrant/.ssh/authorized_keys
                 owner=vagrant
                 group=vagrant
                 mode=0600

      - name: Disable DNS lookup for SSH 
        shell: "echo 'UseDNS no' >> /etc/ssh/sshd_config"

      - name: Prepare disk for compression
        script: /tmp/packer-provisioner-ansible-local/scripts/zero-out-disk.sh
