---
# The playbook will configure the bare minimum needed for an Ubuntu server.

- hosts: all
  sudo: yes
  gather_facts: yes
  tasks:
   - apt: name=tree state=present update_cache=true cache_valid_time=600

